### ISSUE TITLE
Reset the app and apply the nextjs architecture

### ISSUE THREAD

**Issue by wesleydmscn** [flow-erp/client#3]
### Todo

- [x] Create a separate branch to resolve this issue with name nextjs-architecture
- [x] Remove default styles from next.js and assets
- [x] Apply the architecture where it is already possible following the [wiki](https://github.com/flow-erp/client/wiki/nextjs-architecture) standard
- [ ] Post a pull request with details about your additions and reference this issue.
