### ISSUE TITLE
Prepare Environment for Testing: Implement Unit, Integration, and End-to-End Tests

### ISSUE THREAD

**Issue by wesleydmscn** [flow-erp/client#5]
## Todo

1. Install and Configure Vitest:

- [x] Add the necessary dependencies for Vitest in the project's package.json file. 2fa6a1c776686dcb8f51de2694e2b11cbdb634bb
- [x] Set up the Vitest configuration file with appropriate settings. 625502be9b8392b6113e30159a1b2ae71a3be910

2. Install and Configure Cypress:
- [x] Add Cypress as a development dependency in the project's package.json file. 2fa6a1c776686dcb8f51de2694e2b11cbdb634bb
- [x] Set up the Cypress configuration file with required settings, such as test directory and browser options. 781c400f9d204e0df3d2608dbf3cef00d330e4ad
